#!/bin/bash

DEBUG=0
INPUT=../raw/vs_ead.xml
OUTPUT=../graphs/vs_ead.xml
XSLT=convert-vs-eadxml2rdf.xsl


while [ $# -gt 0 ]
do
	if [ "$1" = "--debug" ]; then
		DEBUG=1
	fi

	shift
done


if [ $DEBUG -eq 1 ]; then
	xsltproc --novalid --nonet --nodtdattr $XSLT $INPUT | xmllint --format - > $OUTPUT
else
	xsltproc --novalid --nonet --nodtdattr $XSLT $INPUT > $OUTPUT
fi
